import { Header } from "@/components/layout/header";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-background text-foreground font-sans">
            <Header />
            <main className="pt-32 pb-20 md:pt-48 md:pb-32 px-6 container mx-auto max-w-3xl prose prose-muted prose-headings:font-display prose-headings:font-medium prose-a:text-violet-500 hover:prose-a:text-violet-400">
                <h1>Terms of Service</h1>
                <p className="lead">Last updated: February 9, 2026</p>

                <h2>1. Introduction</h2>
                <p>Welcome to BonusLYF ("we," "our," or "us"). By accessing or using our website, mobile application, and AI companion services (collectively, the "Service"), you agree to be bound by these Terms of Service ("Terms").</p>

                <h2>2. Use of AI Services</h2>
                <p>BonusLYF provides AI-driven companionship. You acknowledge that:</p>
                <ul>
                    <li>The AI is not a human and its responses are generated by machine learning models.</li>
                    <li>The AI is NOT a substitute for professional medical, legal, or financial advice.</li>
                    <li>If you are in crisis or need emergency assistance, please contact local emergency services immediately.</li>
                </ul>

                <h2>3. User Accounts</h2>
                <p>You must be at least 18 years old to use BonusLYF. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</p>

                <h2>4. Intellectual Property</h2>
                <p>The Service and its original content (excluding content provided by you), features, and functionality are and will remain the exclusive property of BonusLYF and its licensors.</p>

                <h2>5. Termination</h2>
                <p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>

                <h2>6. Limitation of Liability</h2>
                <p>In no event shall BonusLYF, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>

                <h2>7. Changes</h2>
                <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will use reasonable efforts to provide at least 30 days' notice prior to any new terms taking effect.</p>

                <h2>8. Contact Us</h2>
                <p>If you have any questions about these Terms, please contact us at <a href="mailto:legal@bonuslyf.com">legal@bonuslyf.com</a>.</p>
            </main>
        </div>
    );
}
